# Generated by Django 6.0.2 on 2026-02-13 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('event_type', models.CharField(choices=[('transaction.created', 'Transaction Created'), ('habit.completed', 'Habit Completed'), ('tier.upgraded', 'Tier Upgraded')], max_length=50)),
                ('secret_key', models.CharField(default=uuid.uuid4, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
