# Generated by Django 6.0.2 on 2026-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='facial_recognition_image',
            field=models.ImageField(blank=True, null=True, upload_to='facial_recognition_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
