# Generated by Django 6.0.2 on 2026-07-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_tier_alter_user_bvn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_save_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
